#!/usr/bin/env python3
"""Fail-closed check of the strict A=3 endpoint norm route fence (2026-07-26).

Claim being certified (see notes/strict_endpoint_norm_route_fence_20260726.md):
the multiplicative/norm comparison on the transposed endpoint factorization

    (X - x_0) * prod_{gamma in Z} Q_gamma(X) = kappa * (X^N - c)^m

yields (NORM)  prod_gamma pi_gamma = (-c)^m / x_0,  pi_gamma = prod_{x in Rt(gamma)} x,

which is an IDENTITY forced by the covering ledger rather than a constraint --
so it excludes nothing and the route is dead.

Two independent certifications, both exact:

  1. COMBINATORIAL UNIVERSALITY.  On small analogues, build many random set
     systems {Rt(gamma)} with the endpoint multiplicities (every domain point
     covered m times except one covered m-1) WITHOUT any algebraic realizability,
     and confirm (NORM) holds for every one of them.  A test that passes on
     arbitrary combinatorial data cannot discriminate algebraic configurations.

  2. 2-ADIC VACUITY AT OFFICIAL SCALE.  In the cyclic form the congruence reduces
     to m * N/2 == 0 (mod N).  At m = 2^37, N = 2^41 this is 2^77 == 0 (mod 2^41),
     true with 36 powers of two to spare -- not a near-miss.

Stdlib only, exact integers, no floats.  No randomness that affects the verdict:
the pseudo-random set systems are generated by a fixed deterministic LCG.
"""

from __future__ import annotations

import sys

M_OFF = 2**37
N_OFF = 16 * M_OFF                      # 2^41
RHO_OFF = 4 * M_OFF - 1
T_OFF = 4 * M_OFF + 1

errors: list[str] = []


def check(cond: bool, msg: str) -> None:
    if not cond:
        errors.append(msg)


# ---------------------------------------------------------------- scale sanity
check(N_OFF == 2**41, "official N drift")
check(RHO_OFF == 4 * M_OFF - 1, "rho drift")
# Endpoint incidence ledger: T*rho = N*m - 1 at h=0, O=0.
check(T_OFF * RHO_OFF == N_OFF * M_OFF - 1,
      f"endpoint incidence identity fails: {T_OFF*RHO_OFF} != {N_OFF*M_OFF-1}")
# Degree check of the transposed normal form.
check(1 + T_OFF * RHO_OFF == N_OFF * M_OFF, "transposed normal form degree mismatch")
# |Rt(gamma)| = rho is odd, which is what turns Q_gamma(0) into -c_gamma*pi_gamma.
check(RHO_OFF % 2 == 1, "rho must be odd for the constant-term sign used")
check((T_OFF + 1) % 2 == 0, "(-1)^(T+1) sign used in the derivation")


# --------------------------------------------- 1. combinatorial universality
def lcg(seed: int):
    state = seed
    while True:
        state = (6364136223846793005 * state + 1442695040888963407) % (1 << 64)
        yield state >> 33


def build_cover(n_dom: int, t: int, rho: int, m: int, rng) -> tuple[int, list[list[int]]] | None:
    """A set system of t subsets, each of rho DISTINCT points of range(n_dom), in
    which every point is covered m times except one point x_0 covered m-1 times.

    Filled by repeatedly taking the rho points of largest remaining capacity
    (pseudo-random tie-break), which realizes any feasible degree sequence -- the
    naive shuffle-and-deal almost never yields distinct blocks."""
    if t * rho != n_dom * m - 1 or rho > n_dom or m > t:
        return None
    x0 = next(rng) % n_dom
    cap = [m - 1 if x == x0 else m for x in range(n_dom)]
    sets = []
    for _ in range(t):
        order = sorted(range(n_dom), key=lambda x: (-cap[x], next(rng)))
        block = order[:rho]
        if any(cap[x] <= 0 for x in block):
            return None
        for x in block:
            cap[x] -= 1
        sets.append(block)
    if any(c != 0 for c in cap):
        return None
    return (x0, sets)


# Small analogues with the endpoint's exact shape: pick m, then N=16m, rho=4m-1,
# T=4m+1 so that T*rho = N*m - 1 holds identically (it does for every m).
rng = lcg(20260726)
tested = 0
for m in (1, 2, 3, 4):
    n_dom, rho, t = 16 * m, 4 * m - 1, 4 * m + 1
    check(t * rho == n_dom * m - 1, f"analogue ledger fails at m={m}")
    attempts = 0
    built = 0
    while built < 40 and attempts < 4000:
        attempts += 1
        res = build_cover(n_dom, t, rho, m, rng)
        if res is None:
            continue
        x0, sets = res
        built += 1
        tested += 1
        # Work in the cyclic group Z/n_dom written additively (exponents a_x),
        # which is exactly the mu_N exponent form; the coset factor d_0 cancels
        # because every subset has the same size rho.
        lhs = sum(sum(block) for block in sets) % n_dom
        # (NORM) in exponents: sum_gamma sum_{x in Rt} a_x  ==  m*sum_x a_x - a_{x0}
        rhs = (m * (n_dom * (n_dom - 1) // 2) - x0) % n_dom
        check(lhs == rhs,
              f"(NORM) FAILED on a combinatorial cover at m={m} -- the fence is wrong")
    check(built >= 40, f"could not build 40 covers at m={m} (built {built})")

check(tested == 160, f"expected 160 covers tested, got {tested}")

# Discriminating-power self-test.  (NORM) is not vacuous as an equation -- it DOES
# detect a cover whose multiplicities are wrong.  What the fence says is narrower
# and sharper: it tests ONLY the covering multiplicities, which the incidence
# ledger already forces, and never the algebraic realizability on top of them.
rng2 = lcg(99991)
caught = 0
trials = 0
for m in (2, 3):
    n_dom, rho, t = 16 * m, 4 * m - 1, 4 * m + 1
    while trials < 20:
        res = build_cover(n_dom, t, rho, m, rng2)
        if res is None:
            continue
        x0, sets = res
        trials += 1
        # Move one incidence from one subset to another point: multiplicities break.
        blk = sets[next(rng2) % t]
        pos = next(rng2) % rho
        old = blk[pos]
        new = (old + 1 + next(rng2) % (n_dom - 1)) % n_dom
        if new == old or new in blk:
            continue
        blk[pos] = new
        lhs = sum(sum(b) for b in sets) % n_dom
        rhs = (m * (n_dom * (n_dom - 1) // 2) - x0) % n_dom
        if lhs != rhs:
            caught += 1
check(caught > 0,
      "(NORM) never detected a corrupted cover -- the equation would be vacuous "
      "as an equation, which is a stronger and different claim than the fence")


# ------------------------------------------------ 2. 2-adic vacuity, official
# sum_{x in D} a_x = N(N-1)/2 == N/2 (mod N) for N even.
s_a = (N_OFF * (N_OFF - 1) // 2) % N_OFF
check(s_a == N_OFF // 2, f"sum of exponents drift: {s_a} != {N_OFF//2}")
# The congruence is vacuous iff m * (N/2) == 0 (mod N).
prod = M_OFF * (N_OFF // 2)
check(prod % N_OFF == 0,
      f"official 2-adic congruence is NOT vacuous: {prod} mod {N_OFF} = {prod % N_OFF}")
# ...and by how much, so nobody mistakes it for a near-miss.
margin = prod.bit_length() - N_OFF.bit_length()
check(margin == 36, f"2-adic margin drift: {margin} != 36")
check(prod == 2**77, f"m*(N/2) drift: {prod} != 2^77")

# Vacuity must NOT be an accident of the official scale only -- confirm it is
# scale-dependent, i.e. the check genuinely could have had content at small m.
# At m=1, N=16: m*(N/2) = 8, and 8 mod 16 = 8 != 0, so the congruence has content
# there.  That is what makes part 1 (universality) the load-bearing argument.
check((1 * (16 // 2)) % 16 != 0,
      "small-scale congruence should have content; if not, part 1 is the only argument")

if errors:
    for e in errors:
        print("FAIL:", e)
    sys.exit(1)

print(
    "STRICT_ENDPOINT_NORM_FENCE_PASS "
    f"covers_tested={tested} (NORM holds on every combinatorial cover) "
    f"official m*(N/2)=2^{prod.bit_length()-1} vs N=2^{N_OFF.bit_length()-1} "
    f"margin={margin} powers of two -- route is dead, not a near-miss"
)
