#!/usr/bin/env python3
"""Fresh-context spot-check of Codex's W2 proof.md qcore construction
(background/nodes/ww_lower_witnesses/proof.md @ cda1b62 / pin 0933bb9).

Claim replayed: on evaluation domain D = multiplicative subgroup of order n
in F_q, with dyadic quotient order N | n, M = n/N, k = rho*n, sigma = M-1,
received word Y(X) = X^k * L_T0(X) for a sigma-subset T0 of one order-M
coset C0, the family P_A(X) = L_T0(X) * (X^k - L_A(X)) over (k/M)-subsets A
of the other N-1 cosets gives EXACTLY C(N-1, k/M) DISTINCT codewords
(deg <= k-1), each agreeing with Y on >= k+sigma points of D.

Checked from scratch by brute polynomial arithmetic mod q (no reuse of any
repo code). Also mutation controls:
  M1: sigma = M           -> degree becomes k (not a codeword) - must FAIL
  M2: T0 drawn from a coset in A's range (non-disjoint)        - agreement
      count logic must be re-derived; we verify disjointness is load-bearing
  M3: wrong locator (generic k-subset, not coset union)        -> X^k - L_A
      has degree k-1 full, P_A degree k+sigma-1 > k-1 for sigma>=1? no:
      deg(X^k - L_A) = k-1 generic, deg P_A = sigma+k-1 > k-1 when sigma>=1
      -> not a codeword unless coset structure kills M-1 coefficients.
All arithmetic exact ints mod q. RAM trivial.
"""
from itertools import combinations
from math import comb
import sys

def polmul(a, b, q):
    r = [0]*(len(a)+len(b)-1)
    for i, x in enumerate(a):
        if x:
            for j, y in enumerate(b):
                r[i+j] = (r[i+j] + x*y) % q
    return r

def poleval(p, x, q):
    acc = 0
    for c in reversed(p):
        acc = (acc*x + c) % q
    return acc

def deg(p):
    d = -1
    for i, c in enumerate(p):
        if c % P: d = i
    return d

def find_gen_subgroup(q, n):
    # find element of multiplicative order exactly n in F_q*
    for g in range(2, q):
        # order of g divides q-1; check g^n == 1 and g^(n/p) != 1 for prime p|n
        if pow(g, n, q) != 1:
            continue
        ok = True
        m = n
        f = 2
        primes = set()
        while m > 1:
            while m % f == 0:
                primes.add(f); m //= f
            f += 1
        for pr in primes:
            if pow(g, n//pr, q) == 1:
                ok = False; break
        if ok:
            return g
    raise RuntimeError("no order-n element")

def run_case(q, n, N, rho_num, rho_den, verbose=True):
    global P
    P = q
    assert (q-1) % n == 0
    M = n // N
    k = n * rho_num // rho_den
    sigma = M - 1
    h = k // M
    assert k % M == 0 and h == rho_num * N // rho_den and 1 <= sigma < M
    g = find_gen_subgroup(q, n)
    D = [pow(g, i, q) for i in range(n)]
    assert len(set(D)) == n
    # order-M subgroup of D: generated by g^N
    H = [pow(g, N*i, q) for i in range(M)]
    # cosets of H in D: u_j = g^j, j = 0..N-1
    cosets = [[(pow(g, j, q)*x) % q for x in H] for j in range(N)]
    flat = sorted(x for c in cosets for x in c)
    assert flat == sorted(D), "cosets do not partition D"
    C0 = cosets[0]
    T0 = C0[:sigma]
    # L_T0
    LT0 = [1]
    for t in T0:
        LT0 = polmul(LT0, [(-t) % q, 1], q)
    # Y(X) = X^k * L_T0(X)
    Y = [0]*k + LT0
    words = {}
    others = list(range(1, N))
    for A in combinations(others, h):
        # L_A = prod over cosets j in A of (X^M - u_j^M)
        LA = [1]
        for j in A:
            f = [0]*(M+1); f[M] = 1; f[0] = (-pow(pow(g, j, q), M, q)) % q
            LA = polmul(LA, f, q)
        assert deg(LA) == k
        # X^k - L_A
        XkmLA = [(-c) % q for c in LA]
        XkmLA[k] = (XkmLA[k] + 1) % q
        d1 = deg(XkmLA)
        assert d1 <= k - M, f"deg(X^k-L_A)={d1} > k-M={k-M}"
        PA = polmul(LT0, XkmLA, q)
        dPA = deg(PA)
        assert dPA <= k - 1, f"P_A degree {dPA} not < k={k}"
        # agreement with Y on D
        agree = [x for x in D if poleval(PA, x, q) == poleval(Y, x, q)]
        UA = sorted(x for j in A for x in cosets[j])
        expected = sorted(set(T0) | set(UA))
        assert set(expected) <= set(agree), "T0 u U_A not all agreements"
        assert len(agree) >= k + sigma, f"agreement {len(agree)} < k+sigma={k+sigma}"
        key = tuple(c % q for c in PA[:k])
        assert key not in words, "collision: P_A not distinct"
        words[key] = (A, len(agree))
    cnt = len(words)
    assert cnt == comb(N-1, h), (cnt, comb(N-1, h))
    # Y itself must NOT be a codeword (deg k+sigma >= k)
    assert deg(Y) == k + sigma >= k
    if verbose:
        agrees = sorted(set(v[1] for v in words.values()))
        print(f"  q={q} n={n} N={N} M={M} k={k} sigma={sigma}: "
              f"{cnt} = C({N-1},{h}) distinct codewords, all deg<=k-1, "
              f"agreement>=k+sigma={k+sigma} PASS (agreement sizes seen: {agrees})")
    return True

def mutation_sigma_eq_M(q, n, N, rho_num, rho_den):
    """sigma = M: T0 = full coset C0. P_A degree must be k (NOT a codeword)."""
    global P
    P = q
    M = n // N
    k = n * rho_num // rho_den
    h = k // M
    g = find_gen_subgroup(q, n)
    H = [pow(g, N*i, q) for i in range(M)]
    cosets = [[(pow(g, j, q)*x) % q for x in H] for j in range(N)]
    T0 = cosets[0]           # sigma = M
    LT0 = [1]
    for t in T0:
        LT0 = polmul(LT0, [(-t) % q, 1], q)
    from itertools import combinations as C_
    A = next(iter(C_(range(1, N), h)))
    LA = [1]
    for j in A:
        f = [0]*(M+1); f[M] = 1; f[0] = (-pow(pow(g, j, q), M, q)) % q
        LA = polmul(LA, f, q)
    XkmLA = [(-c) % q for c in LA]
    XkmLA[k] = (XkmLA[k] + 1) % q
    PA = polmul(LT0, XkmLA, q)
    d = deg(PA)
    assert d == k, f"mutation not detected: deg={d}, expected k={k}"
    print(f"  MUTATION sigma=M: deg(P_A) = {d} = k -> NOT a codeword; "
          f"construction correctly requires sigma < M")

def mutation_generic_locator(q, n, N, rho_num, rho_den):
    """Non-coset k-subset: X^k - L_A generically has degree k-1, so
    P_A has degree k+sigma-1 > k-1 -> not a codeword. Coset structure is
    load-bearing."""
    global P
    P = q
    M = n // N
    k = n * rho_num // rho_den
    sigma = M - 1
    g = find_gen_subgroup(q, n)
    D = [pow(g, i, q) for i in range(n)]
    H = [pow(g, N*i, q) for i in range(M)]
    cosets = [[(pow(g, j, q)*x) % q for x in H] for j in range(N)]
    T0 = cosets[0][:sigma]
    LT0 = [1]
    for t in T0:
        LT0 = polmul(LT0, [(-t) % q, 1], q)
    # generic k-subset avoiding C0: shift one element between two cosets
    pool = sorted(x for c in cosets[1:] for x in c)
    S = pool[:k-1] + [pool[k]]   # k points, NOT a coset union
    LA = [1]
    for t in S:
        LA = polmul(LA, [(-t) % q, 1], q)
    XkmLA = [(-c) % q for c in LA]
    XkmLA[k] = (XkmLA[k] + 1) % q
    PA = polmul(LT0, XkmLA, q)
    d = deg(PA)
    assert d > k - 1, f"generic locator unexpectedly gave codeword degree {d}"
    print(f"  MUTATION generic k-set locator: deg(P_A) = {d} > k-1 -> not a "
          f"codeword; the order-M coset-union structure is load-bearing")

if __name__ == "__main__":
    print("qcore construction spot-check (independent, brute polynomial arithmetic):")
    # rho = 1/4 analogues
    run_case(97, 16, 8, 1, 4)      # M=2, sigma=1, C(7,4)... h=4? k=4,h=2 -> C(7,2)=21
    run_case(193, 32, 8, 1, 4)     # M=4, sigma=3, k=8, h=2, C(7,2)=21
    run_case(257, 16, 8, 1, 8)     # M=2, sigma=1, k=2, h=1, C(7,1)=7
    run_case(97, 32, 16, 1, 16)    # M=2, sigma=1, k=2, h=1, C(15,1)=15
    run_case(193, 64, 16, 1, 4)    # M=4, sigma=3, k=16, h=4, C(15,4)=1365
    mutation_sigma_eq_M(97, 16, 8, 1, 4)
    mutation_generic_locator(193, 32, 8, 1, 4)
    # margins claimed in master + Codex proof:
    from math import log2
    def lg(c):
        b = c.bit_length()
        return b - 53 + log2(c >> (b-53)) if b > 53 else log2(c)
    for (N, h, banked) in ((256, 64, 75.15), (256, 32, 7.23), (512, 32, 40.82)):
        m = lg(comb(N-1, h)) - 128
        print(f"  margin C({N-1},{h}) vs 2^128: {m:+.4f} bits (banked {banked:+.2f}) "
              f"match={abs(m-banked)<0.01}")
    assert comb(127, 64) < (1 << 128), "rate-1/2 must remain uncovered"
    print(f"  rate-1/2: log2 C(127,64) = {lg(comb(127,64)):.2f} < 128 -> correctly excluded")
    print("ALL SPOT-CHECKS PASS")
