#!/usr/bin/env python3
"""Verify the fiber-two path exclusion packet and its sharp controls."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
NODE = "rate_half_list_budget_three_fiber_two_path_exclusion"
DEPENDENCY = "rate_half_list_budget_three_multifiber_vandermonde_exclusion"
CONSUMER = "rate_half_list_adjacent_crossing"
PRIME = 101


def add(left: list[int], right: list[int]) -> list[int]:
    size = max(len(left), len(right))
    return [
        ((left[i] if i < len(left) else 0) + (right[i] if i < len(right) else 0))
        % PRIME
        for i in range(size)
    ]


def scale(value: int, polynomial: list[int]) -> list[int]:
    return [value * coefficient % PRIME for coefficient in polynomial]


def multiply(left: list[int], right: list[int]) -> list[int]:
    answer = [0] * (len(left) + len(right) - 1)
    for i, a in enumerate(left):
        for j, b in enumerate(right):
            answer[i + j] = (answer[i + j] + a * b) % PRIME
    return answer


def lift_even(polynomial: list[int]) -> list[int]:
    answer = [0] * (2 * len(polynomial) - 1)
    for index, coefficient in enumerate(polynomial):
        answer[2 * index] = coefficient
    return answer


def trim(polynomial: list[int]) -> list[int]:
    while len(polynomial) > 1 and polynomial[-1] == 0:
        polynomial.pop()
    return polynomial


def identity_checks() -> int:
    checked = 0
    for roots in ((2, 5, 9), (2, PRIME - 2, 9)):
        common = [7, 11, 1]
        weights = (
            (roots[1] - roots[2]) % PRIME,
            (roots[2] - roots[0]) % PRIME,
            (roots[0] - roots[1]) % PRIME,
        )
        locators = [
            multiply([root, 1], lift_even(common))
            for root in roots
        ]
        relation = [0]
        for weight, locator in zip(weights, locators, strict=True):
            relation = add(relation, scale(weight, locator))
        assert trim(relation) == [0]
        assert len(lift_even(common)) > 1

        mutated = weights[0], weights[1], (weights[2] + 1) % PRIME
        bad_relation = [0]
        for weight, locator in zip(mutated, locators, strict=True):
            bad_relation = add(bad_relation, scale(weight, locator))
        assert trim(bad_relation) != [0]
        checked += 1

    roots = (2, 5, 9)
    weights = (
        (roots[1] - roots[2]) % PRIME,
        (roots[2] - roots[0]) % PRIME,
        (roots[0] - roots[1]) % PRIME,
    )
    sharp_locators = [[root, 1] for root in roots]
    relation = [0]
    for weight, locator in zip(weights, sharp_locators, strict=True):
        relation = add(relation, scale(weight, locator))
    assert trim(relation) == [0]
    checked += 1
    return checked


def packet_check() -> None:
    dag = json.loads((ROOT / "dag.json").read_text())
    nodes = {node["id"]: node for node in dag["nodes"]}
    edges = {(edge["from"], edge["to"], edge["kind"]) for edge in dag["edges"]}
    assert nodes[NODE]["status"] == "PROVED"
    assert nodes[DEPENDENCY]["status"] == "PROVED"
    assert (DEPENDENCY, NODE, "req") in edges
    assert (NODE, CONSUMER, "ev") in edges

    here = ROOT / "background" / "nodes" / NODE
    statement = (here / "statement.md").read_text()
    proof = (here / "proof.md").read_text()
    for marker in (
        "A_i(X)=(X+r_i)K_i(X^2)",
        "lambda_0 lambda_1 lambda_2!=0",
        "deg K=s-1>=1",
        "common map `X^2`",
        "four-cycle",
    ):
        assert marker in statement
    for marker in (
        "opposite parity",
        "kernel is generated by",
        "K(X^2)` divides every `A_i`",
        "s=2^38>=2",
    ):
        assert marker in proof


def main() -> None:
    checked = identity_checks()
    assert (1 << 39) // 2 == 1 << 38
    packet_check()
    print(
        "RATE_HALF_LIST_B3_FIBER_TWO_PATH_EXCLUSION_PASS "
        f"controls={checked} antipodal=1 sharp_s1=1 mutation=1"
    )


if __name__ == "__main__":
    main()
