"""r35 D1 -- ROUTES (a), (b), (c) at m = 4, in ONE currency.

(b) sigma(x) = c/x .  R1.1/R2.1 are verified first, THEN searched.
(c) un-symmetrised: three independent degree-3 pencils, no sharing.
(a) NON-SPLIT G.  The sub-route named here is new and is NOT inside
    (SPLIT-4):

      (QUAD-4)   G(Z,x) = Q(Z,u) * L(Z,u) ,  u = x^2
                 Q = A(u)Z^2 + B(u)Z + C(u) ,  deg_u A,B,C <= 3
                 L = S(u)Z - R(u)           ,  deg_u R,S <= 1

    Q is IRREDUCIBLE over F_q(u) for generic (A,B,C) -- so G does not
    factor into linear-in-Z factors over F_q(x) and this is genuinely
    route (a) -- yet Q is sigma-INVARIANT, so its two roots are shared by
    the orbit {x,-x} exactly as (SPLIT-4)'s swapped pair is.  Its roots
    are in F_q at an orbit iff disc = B^2-4AC is a square there.

    PARAMETER COUNT:  (SPLIT-4) = 7 (A,B deg 3, projective) + 3 (Mobius in
    u) = 10.  (QUAD-4) = 11 (A,B,C deg_u 3, projective) + 3 = 14.
    (SPLIT-4) is the sub-family where disc is a square IN F_q(u).
    So route (a) buys FOUR parameters and pays ~24 square-conditions.

    Also derived here: at EVEN m every sigma-symmetric ansatz wastes one
    unit of the 3m-3 x-degree budget, because a sigma-invariant factor has
    EVEN x-degree (3+3+2 = 8 < 9 split; 6+2 = 8 < 9 quadratic).

Stdlib only.  Checkpointed.
"""

import random
import sys
import time

T0 = time.time()
DEADLINE = float(sys.argv[1]) if len(sys.argv) > 1 else 240.0
CK = "notes/pilots_20260811/r35_bivcurve_m4/route_bc_ckpt.txt"
out = []
P = out.append


def ckpt(s):
    with open(CK, "a") as fh:
        fh.write("%7.1fs %s\n" % (time.time() - T0, s))


def mu_N(q, n):
    for c in range(2, q):
        g = pow(c, (q - 1) // n, q)
        seen, x = set(), 1
        for _ in range(n):
            seen.add(x)
            x = x * g % q
        if len(seen) == n:
            return sorted(seen)
    raise RuntimeError


def cev(c, x, q):
    v = 0
    for co in reversed(c):
        v = (v * x + co) % q
    return v


def sqrt_mod(a, q):
    if a == 0:
        return 0
    if pow(a, (q - 1) // 2, q) != 1:
        return None
    if q % 4 == 3:
        return pow(a, (q + 1) // 4, q)
    for r in range(1, q):          # q = 193, 257 are small; direct search ok
        if r * r % q == a:
            return r
    return None


def best_sel(tuples, nedge, degcap, nslope, paircap, budget):
    n = len(tuples)
    deg, pair, chosen = {}, {}, []
    best = [0, []]
    cnt = [0]

    def rec(i):
        if cnt[0] > budget:
            return
        cnt[0] += 1
        if len(chosen) > best[0]:
            best[0] = len(chosen)
            best[1] = list(chosen)
        if len(chosen) == nedge:
            return
        if len(chosen) + (n - i) <= best[0]:
            return
        for j in range(i, n):
            t = tuples[j]
            if any(deg.get(z, 0) >= degcap for z in t):
                continue
            ks = [(min(t[p], t[r]), max(t[p], t[r]))
                  for p in range(len(t)) for r in range(p + 1, len(t))]
            if any(pair.get(k2, 0) >= paircap for k2 in ks):
                continue
            newv = len({z for z in t if z not in deg})
            if len(deg) + newv > nslope:
                continue
            for z in t:
                deg[z] = deg.get(z, 0) + 1
            for k2 in ks:
                pair[k2] = pair.get(k2, 0) + 1
            chosen.append(j)
            rec(j + 1)
            chosen.pop()
            for k2 in ks:
                pair[k2] -= 1
                if pair[k2] == 0:
                    del pair[k2]
            for z in t:
                deg[z] -= 1
                if deg[z] == 0:
                    del deg[z]
            if cnt[0] > budget:
                return

    rec(0)
    return best[0], best[1]


P("=" * 78)
P("r35 D1 -- ROUTES (a)/(b)/(c) AT m = 4")
P("=" * 78)
P("")

# ------------------------------------------------------ R2.1 / R1.1 for (b)
P("-" * 78)
P("(b0)  ORBIT ARITHMETIC OF sigma(x) = c/x ON mu_64, DERIVED BEFORE SEARCH")
for q in (193, 257):
    D = mu_N(q, 64)
    Dset = set(D)
    sq = {x * x % q for x in D}          # = mu_32
    nfix = {}
    for c in D:
        f = sum(1 for x in D if x * x % q == c)
        nfix[f] = nfix.get(f, 0) + 1
    P("  q=%d : c must lie in mu_64 (else sigma leaves mu_64); #fixed points"
      " over c in mu_64 : %s" % (q, sorted(nfix.items())))
    P("         squares (mu_32) : %d values of c give 2 fixed points ; the"
      " other %d give 0 -- NEVER ODD  [R2.1 confirmed]"
      % (nfix.get(2, 0), nfix.get(0, 0)))
    P("         |S_g ^ S_h| = m-1 = 3 is ODD, so W can never be sigma-stable"
      " at even m  [R2.3 confirmed]")

P("")
P("(b1)  R1.1: IS A sigma-INVARIANT FACTOR STILL INJECTIVE ON ORBITS?")
P("      invariants of x -> c/x are generated by w = x + c/x, so a factor")
P("      with chi(c/x) = chi(x) and deg_x <= 3 reduces to a MOBIUS map in w.")
for q in (193, 257):
    D = mu_N(q, 64)
    rnd = random.Random(9000 + q)
    c = None
    for cc in D:                       # pick c a square in mu_64 -> 2 fixed pts
        if sum(1 for x in D if x * x % q == cc) == 2:
            c = cc
            break
    orbits, seen = [], set()
    for x in D:
        if x in seen:
            continue
        y = c * pow(x, q - 2, q) % q
        seen.add(x)
        seen.add(y)
        orbits.append((x, y))
    nfix = sum(1 for (x, y) in orbits if x == y)
    inj = []
    for _ in range(200):
        p, r, s, t = [rnd.randrange(q) for _ in range(4)]
        if (p * t - r * s) % q == 0:
            continue
        vals = []
        ok = True
        for (x, y) in orbits:
            w = (x + c * pow(x, q - 2, q)) % q
            den = (s * w + t) % q
            if den == 0:
                ok = False
                break
            vals.append((p * w + r) % q * pow(den, q - 2, q) % q)
        if ok:
            inj.append(len(set(vals)) == len(vals))
    P("  q=%d c=%d : %d orbits (%d fixed points) ; Mobius-in-w factors tested"
      " %d ; INJECTIVE ON ORBITS in %d of them"
      % (q, c, len(orbits), nfix, len(inj), sum(inj)))
    # brute-force confirmation: ALL deg<=3 invariant factors are Mobius in w
    hits, tested = 0, 0
    for _ in range(4000):
        A = [rnd.randrange(q) for _ in range(4)]
        B = [rnd.randrange(q) for _ in range(4)]
        okinv, vals = True, []
        for (x, y) in orbits:
            bx, by = cev(B, x, q), cev(B, y, q)
            if bx == 0 or by == 0:
                okinv = False
                break
            v1 = cev(A, x, q) * pow(bx, q - 2, q) % q
            v2 = cev(A, y, q) * pow(by, q - 2, q) % q
            if v1 != v2:
                okinv = False
                break
            vals.append(v1)
        if okinv:
            tested += 1
            if len(set(vals)) == len(vals):
                hits += 1
    P("       random deg<=3 phi that happen to be sigma-invariant on mu_64:"
      " %d found, %d of them injective on orbits" % (tested, hits))
P("  ==> R1.1 CONFIRMED: route (b) does NOT remove the injective-on-orbits")
P("      factor.  The brief's hypothesis that the fixed points change the")
P("      cross-coincidence term is REFUTED at the derivation level.")

# ---------------------------------------------------------------- searches
def run_route(tag, q, mode, trials, seed, budget, nedge, degcap, nslope,
              paircap):
    D = mu_N(q, 64)
    rnd = random.Random(seed)
    if mode == "b":
        c = None
        for cc in D:
            if sum(1 for x in D if x * x % q == cc) == 2:
                c = cc
                break
        orbits, seen = [], set()
        for x in D:
            if x in seen:
                continue
            y = c * pow(x, q - 2, q) % q
            seen.add(x)
            seen.add(y)
            if x != y:
                orbits.append((x, y))
    else:
        orbits, seen = [], set()
        for x in D:
            if x in seen:
                continue
            y = (q - x) % q
            seen.add(x)
            seen.add(y)
            orbits.append((x, y))
    hist, best, ndisc = {}, 0, []
    done = 0
    for tr in range(trials):
        if time.time() - T0 > DEADLINE:
            break
        tri = []
        if mode in ("b", "c"):
            A = [rnd.randrange(q) for _ in range(4)]
            B = [rnd.randrange(q) for _ in range(4)]
            if mode == "b":
                p, r, s, t = [rnd.randrange(q) for _ in range(4)]
                if (p * t - r * s) % q == 0:
                    continue
                for (x, y) in orbits:
                    bx, by = cev(B, x, q), cev(B, y, q)
                    w = (x + c * pow(x, q - 2, q)) % q
                    den = (s * w + t) % q
                    if bx == 0 or by == 0 or den == 0:
                        continue
                    v1 = cev(A, x, q) * pow(bx, q - 2, q) % q
                    v2 = cev(A, y, q) * pow(by, q - 2, q) % q
                    v3 = (p * w + r) % q * pow(den, q - 2, q) % q
                    if len({v1, v2, v3}) == 3:
                        tri.append((v1, v2, v3))
            else:  # (c) un-symmetrised: EVERY point carries its own triple
                A2 = [rnd.randrange(q) for _ in range(4)]
                B2 = [rnd.randrange(q) for _ in range(4)]
                A3 = [rnd.randrange(q) for _ in range(4)]
                B3 = [rnd.randrange(q) for _ in range(4)]
                for x in D:
                    vs, ok = [], True
                    for (AA, BB) in ((A, B), (A2, B2), (A3, B3)):
                        b = cev(BB, x, q)
                        if b == 0:
                            ok = False
                            break
                        vs.append(cev(AA, x, q) * pow(b, q - 2, q) % q)
                    if ok and len(set(vs)) == 3:
                        tri.append(tuple(vs))
        else:  # (a) = (QUAD-4): non-split sigma-invariant quadratic
            Aq = [rnd.randrange(q) for _ in range(4)]
            Bq = [rnd.randrange(q) for _ in range(4)]
            Cq = [rnd.randrange(q) for _ in range(4)]
            R = [rnd.randrange(q) for _ in range(2)]
            S = [rnd.randrange(q) for _ in range(2)]
            nsq = 0
            for (x, y) in orbits:
                u = x * x % q
                av, bv, cv = cev(Aq, u, q), cev(Bq, u, q), cev(Cq, u, q)
                sv = cev(S, u, q)
                if av == 0 or sv == 0:
                    continue
                disc = (bv * bv - 4 * av * cv) % q
                rt = sqrt_mod(disc, q)
                if rt is None or disc == 0:
                    continue
                nsq += 1
                inv2a = pow(2 * av % q, q - 2, q)
                r1 = (-bv + rt) % q * inv2a % q
                r2 = (-bv - rt) % q * inv2a % q
                r3 = cev(R, u, q) * pow(sv, q - 2, q) % q
                if len({r1, r2, r3}) == 3:
                    tri.append((r1, r2, r3))
            ndisc.append(nsq)
        if len(tri) < nedge:
            continue
        done += 1
        s, sl = best_sel(tri, nedge, degcap, nslope, paircap, budget)
        hist[s] = hist.get(s, 0) + 1
        if s > best:
            best = s
        if tr % 50 == 49:
            ckpt("%s q=%d tr=%d best=%d" % (tag, q, tr, best))
    P("  %-28s q=%-4d : %4d draws, tuples avg %s -> BEST = %2d of %2d  hist %s"
      % (tag, q, done, "-", best, nedge, sorted(hist.items())))
    if ndisc:
        P("       orbits with disc a nonzero square: min %d mean %.1f max %d"
          " of %d  (=> Q is NOT split over F_q(u): a split Q would give %d)"
          % (min(ndisc), sum(ndisc) / len(ndisc), max(ndisc), len(orbits),
             len(orbits)))
    return best


P("")
P("-" * 78)
P("(b2)  ROUTE (b) SEARCH: sigma(x) = c/x, 2 fixed points, 31 two-orbits")
P("      need 12 shared triples, deg <= 3, <= 15 slopes, LINEAR")
for q in (193, 257):
    run_route("route(b) c/x", q, "b", 200, 6100 + q, 12000, 12, 3, 15, 1)

P("")
P("-" * 78)
P("(c)   ROUTE (c) SEARCH: un-symmetrised (3,3,3), NO sharing, so all 24")
P("      points of S_g D S_h carry their OWN triple: need 24 of 64, slope")
P("      degree cap 2m-2 = 6, pair multiplicity cap m-1 = 3, <= 15 slopes.")
P("      (this is a RELAXATION -- the per-side caps are not imposed -- so a")
P("      ceiling under it is a genuine ceiling for route (c))")
for q in (193, 257):
    run_route("route(c) unsymmetrised", q, "c", 120, 7100 + q, 12000, 24, 6,
              15, 3)

P("")
P("-" * 78)
P("(a)   ROUTE (a) SEARCH: (QUAD-4), NON-SPLIT sigma-invariant quadratic")
P("      G = Q(Z,u) L(Z,u), Q irreducible over F_q(u); 14 parameters vs")
P("      (SPLIT-4)'s 10.  Same target: 12 shared triples, deg <= 3, <= 15")
P("      slopes, LINEAR.")
for q in (193, 257):
    run_route("route(a) (QUAD-4)", q, "a", 200, 8100 + q, 12000, 12, 3, 15, 1)

P("")
P("=" * 78)
print("\n".join(out))
with open("notes/pilots_20260811/r35_bivcurve_m4/route_bc_results.txt", "w") as f:
    f.write("\n".join(out) + "\n")
