# Maintainer decision lines — 2026-07-13 (post clause-(P) banking)

Three one-edit decisions now carry the entire remaining weight of the
petal lane and the dli amber. Each is stated with its exact required
text, its mechanical effect, and its pre-registered reversal. Nothing
here is auto-executed: every line below waits for the maintainer's own
edit or file.

---

## 1. P1 — the petal band decision (TOP priority; the petal lane's ONLY
##    open item)

**State:** petal_growth is CONDITIONAL with ALL ELEVEN wired hypotheses
PROVED (G1 clause (P), G2, G3 compiler, K4, census gate, the six E22/v13
suppliers). The validator's amber-invariant warning is live ("promote or
re-wire"). The only content between petal_growth and PROVED is pin P1:
the top-defect band posing (conditional.md: "the floor's band is
d >= M(t-2)").

**Decision:** confirm the FLOOR reading (the posing every proved
component consumed, audit-verified layout-anchored), or resolve WIDE.

**To confirm floor**, append this line (or equivalent words) to
`critical/nodes/petal_growth/conditional.md`:

```
MAINTAINER CONFIRMATION (P1): the top-defect band of record is the floor band d >= M(t-2), layout-anchored per catch #168; the wide-band reading is closed as killed (2^59.67 > 2^41.92).
```

**Effect:** petal_growth promotes to PROVED at the next banking pass
(all hypotheses proved + the pin confirmed), closing the petal lane.
The #171 below-top lift mass becomes the single open below-top
quantity, already flagged in the statement.

**Reversal (pre-registered):** tripwire (P)-3 — a later P1
wide-resolution re-opens clause (P), the G3 compiler, and petal_growth
(the kill arithmetic C(63,32) > budget then falsifies the chain's
supply side; this is the honest, pre-registered outcome).

---

## 2. M5 — the dli endpoint one-liner (catch #40)

**State:** the dli amber surgery is EXECUTED (R1 #165 tether + MUT-8,
#162 deletion, M4 statement addendum, #164 display fix). The M4
verifier prints "M5: OUTSTANDING" and its verdict stays
ASSEMBLY-VERIFIED-CONDITIONAL.

**To confirm**, create
`critical/nodes/dli_prime_weighted_large_block_support/notes/M5_CONFIRMATION_2P121.md`
containing exactly this line (the verifier greps it verbatim):

```
MAINTAINER CONFIRMATION (M5, catch #40): the operative endpoint of CONJECTURE B-WEAK and of every dli route document is 2^121 (joint reserve 21 bits); the 2^122 displays are superseded.
```

**Effect:** M4 flips to "M5: CONFIRMED"; dli's route close is amber in
full (three named predicates C2''/C1'/ENDPOINT-EXC, F-round 1/1/1,
machine-verified assembly). Remaining before any promotion: the #166
countersign hardening (spec in m4a_findings.md) and the predicates
themselves.

---

## 3. C2'' — promotion review (slower burn)

**State:** C2'' (the 21-bit joint reserve at the /33 convention) is
CONDITIONAL-posed with one survived pre-registered round (M1 tower
census, Modal). Its promotion path needs: the maintainer's read of
C2PP_POSED_20260710.md against the M1 record, a second adversarial
round if desired, and the #166-hardened countersign gate (no silent
upgrade — the M4 verifier enforces this mechanically).

**No text is owed yet** — this line is a review request, not a
one-liner. The M4 machine consumes any future countersign only through
the hardened gate.

---

*House note: decisions 1 and 2 are one-edit acts with pre-registered
reversals; neither upgrades any mathematics by itself — they pin
POSINGS that every downstream artifact already consumes explicitly.*

---

## 4. WCL-ZONE dedup ratification + the W_cl two-ledger split (from
##    F-round 2, catches #198-#204)

**State:** WCL-ZONE survived rounds 1 and 2 (2/2). Round 2 discharged
the owed dedup canonical spec (#191) — implementation-grade, grounded
in the banked M2 machinery, 12/12 conformance — but exposed a MAJOR
interface finding (#198/wz2-C1): under the pose's own deduplicated
ledger, C1' fails at the banked accident row (K'_dedup = 6.5019 > 4 at
L=1, q=7937; the lift owns 3 canonical orbits via the previously
unpriced admissible N=16 companion). The M3 CORRECTED POSE uses one
symbol W_cl in both the zone bound (<= 1/32) and the C1' allowance —
they cannot be the same ledger.

**Decisions owed:**
(a) The two-ledger split: which ledger (raw vs canonical-deduplicated)
each of the zone bound and the C1' allowance reads. Until ruled, the
baseline node's assembly is flagged BLOCKED AS WRITTEN.
(b) RATIFY-1..8 (full list + defaults in
background/nodes/dli_wcl_zone_coverage/notes/wz2_fround2_20260713/
wz2_dedup_spec.md): two are load-bearing — RATIFY-4 (singular-source
witness scope; the round-7 method is structurally inapplicable to
forced orbits, and official rows with odd(L) > 1 hit this path) and
RATIFY-6 (lift admissibility gate; flips forced mass 12 -> 0 on the
companion's balance condition).

**Effect:** ruling (a)+(b) unblocks certificate work on WCL-ZONE and
re-arms the baseline assembly; nothing else in the dli decomposition
changes (C2'' untouched; the F-round records stand).

---

## 4-REVISED (post wave-7 audit; supersedes the open form of decision 4)

**(a) The two-ledger split is now SETTLED BY THEOREM (wave-7 cluster A,
IMPORT-WITH-REPAIRS):** C1'-as-recorded consumes the RAW ledger by
definition — verified verbatim against the pose file, the dyadic_k_core
statement, and the PRO_DLI_CLOSE_6 lattice frame; the banked M2 record
is raw; substituting a dedup zone bound into raw-C1' is invalid without
a mass-transfer theorem (countermodel: W_owner = 1/256 vs W_raw = 9/256
at ell=16). Catch #198's K'_dedup = 6.5019 was a MISAPPLIED LEDGER;
the banked raw K' = 0.246909432 < 4 stands; the baseline node's
BLOCKED-AS-WRITTEN caveat lifts on your ratification. What remains
yours: the one-line ratification act (raw ledger for BOTH the zone
bound and the C1' allowance); option (b) (re-pose C1' against dedup)
stays formally open but is refuted in its literal K' <= 4 form.

**(c) NEW — schedule r2 ratification (w7-C1, MAJOR):** master's
"N_L = 256L, L = 1..34" display conflates level INDEX with level
DIMENSION. The banked skew-tower packet / S6 / C2'' pin the dyadic
dims ell_j = (2^32, ..., 2, 1, 1) with Sigma = t = 2^33 (the linear
reading sums to 595, contradicting the banked Sigma_j L_j = t
outright). Ratifying schedule r2 re-frames the WCL window in (ell, w)
slots. RATIFY-4/6 become analogue-census-only under this fix
(official rings are all 2-power).

**Effect of ratifying (a)+(c):** WCL-ZONE becomes EQUIVALENT to SIX
finite zero-event emptiness slots on official rows — (ell,w) =
(1,5),(1,6) at order-512 roots; (2,5),(2,6),(2,7) at order 1024
(P(w)=P(w^3)=0); (4,9) at order 2048 — everything else is closed
unconditionally by the audited wave-7 ladder (Newton short-window
w <= 2ell theorem = 30 of 34 levels outright; terminal weight-3/4
exclusions; ell-2 census/Newton). All six slots are q-dependent
(the A1-PROD density-vs-row gap). Full import surgery spec:
notes/kernel_basis/WAVE7_AUDIT_FINDINGS.md.

---

## DECISION 4 — RATIFIED (maintainer, in-session, 2026-07-13: "ok I
## ratify it!")

MAINTAINER RULING (4a): W_cl in WCL-ZONE and in the C1' allowance is
the RAW primitive signed-shift ledger (no first-owner deletion); the
dedup phrase in the M3 corrected pose is struck per w7-C2; wz2-C1 is
recorded as a misapplied-ledger finding; the baseline assembly is
re-armed as written. Pre-registered reversal: a future theorem
re-charging deleted mass to owners may re-introduce a dedup ledger as
a COMPUTATIONAL DEVICE with an explicit W_raw <= f(W_dedup) bridge;
absent that theorem the raw reading stands.

MAINTAINER RULING (4b): the RATIFY-1..8 defaults are ratified as
ANALOGUE-CENSUS bookkeeping conventions (what wz2's module implements,
12/12 conformance); RATIFY-4 and RATIFY-6 are explicitly
non-load-bearing for official certificates under ruling (4a).

MAINTAINER RATIFICATION (4c / w7-C1): the production tower of record
is t = 2^33, ell_j = ceil(floor(t/2^j)/2), dims (2^32,...,2,1,1); the
N_L = 256L displays are superseded (pose revision r2 of
dli_wcl_zone_coverage and dli_marginal_baseline100_coverage). The
F-round records stand as analogue-scale evidence; #190's arithmetic
is schedule-free and its instantiation is annotated, not changed.


---

## DECISION 2 (M5) — RATIFIED + PROCESS CHANGE (2026-07-13, in-session)

M5 RATIFIED: notes/.../M5_CONFIRMATION_2P121.md written; the M4 verifier
prints "M5: CONFIRMED". Catch #40 settled — 2^121 is the operative
endpoint (forced by the catch-#30 complement-duality two-sided split;
the proof clears it with ~20 bits of slack); the 2^122 displays are
superseded.

PROCESS CHANGE (maintainer, standing): FORCED corrections — a pin /
constant / display / schedule with a single mathematically-correct value
(determined by arithmetic, audit, proof, or the strongest-true-reading
principle) — are now applied DIRECTLY, no maintainer queue. This entry's
M5 was the last "decision" of that kind that was queued; going forward
such corrections are just made (banked, reversible, provenance-annotated).
Genuine choices, status flips on named conjectures (the amber ceremony),
and outward-facing acts remain surfaced. Full policy:
memory rs-mca-forced-corrections-authority.md.

## Decision 5 (2026-07-21): w17-C1 — Modal screens accepted; time-based self-authorization

Ruled in-session by the maintainer during the queue walk.

(a) **Evidence — ACCEPTED + REGISTERED.** The three wave-17 Modal no-hit
screens (antiinvariant ap-6KQ2mJjoE3Qkq7VaKqnxlZ; harmonic
ap-Js6Im9DeoBlc0di05YG2WE; harmonic-top ap-PVTrzkKlh4j1B6qDmGU1Wf) are
accepted as PROVED evidence for their three consuming nodes under their
local coverage/hash certificates. Registration executed: per-node
verify_screen_certificate.py (hash-pins packet: checker + launcher +
result.json, runs the checker fail-closed) + verify_screen_remote.py
(manifest remote launcher). Closes w17-C4.

(b) **Policy — RATIFIED AS AMENDED (time-based).** The maintainer's words:
"lets keep the time below 5mins - this is easier than imposing a dollar
cost." The sub-$1 self-authorization criterion is superseded: a launch is
self-authorized iff route-deciding + conservative TOTAL WALL-TIME < 5
minutes (auditable via banked per-shard timings) + certificate/checker
banked + logged in PRIZE_COMPUTE_REQUESTS.md. Everything else = contributor
request. Standing item #260 (9 queued sub-$1 jobs) is settled in principle:
each re-screens under the time rule. The ruled text lives in
notes/PRIZE_COMPUTE_REQUESTS.md ("Maintainer ruling (2026-07-21)"); Codex
should adopt it on its next master merge.

## Decision 6 (2026-07-21): amber-2 accepted — the dli amber ceremony executed

Ruled in-session (queue item 3). The maintainer accepts **amber-2** — any
C1'-r3 row with `K'_r3 >= 2` above the iid asymptote, measured on the
EXTENDED ledger — as the standing watch line for all future evidence rounds
on the dli lane (r3b report condition (iii); conditions (i)/(ii) were already
met). Calibration basis: two survived rounds, worst K' = 1.4016 (2.85x margin
under the never-moved literal-4 kill), zero rows ever >= 2, the [1,2) legacy
band's extreme-value plateau (~1.4, c1r3b-C4), and the extended-window
repricing of the accident row 918552577 (3.000 -> 1.333) as the measurement
of record. CEREMONY EXECUTED same session: `dli_c1r3_gated_envelope_bound`
minted (TARGET, 16-file packet pin); baseline re-armed req (C1'-r3 +
WCL-ZONE-ext) and flipped CONDITIONAL; `dli_prime_weighted_large_block_support`
flipped CONDITIONAL on C2'' + baseline (req), with the route close and
pre-registered demotion criteria in its conditional.md.
