"""D1/F1/F2 at the toy h=8 (exhaustive).  Draft-only; writes to this dir.

SELF-CORRECTION vs my registration R1: BAD(N') is generated by the FULL box
(a bad prime is any odd p dividing Norm(w) for ANY nonzero box w -- Norm(w)
need not be odd).  So the energy bound is E <= 4h (not 4h-3) and
CEIL = (4h)^{h/2}.  Both are recorded here and the toy is redone on the full
box, which also re-derives round-25's exhaustive ground truth as calibration.

  LEM-1  0 < Norm(w) <= E(w)^{h/2} <= (4h)^{h/2} = CEIL          (LN4 + box)
  LEM-2  no box norm has two prime factors > CEIL^{1/2}
  THM-SPARSE  BADCOUNT(W)/PI(W) vs the proved counting bound
  F2     Cochran-Armitage trend of BADFRAC8(v), pooled + dyadic-stratified,
         with the 80%-power minimum detectable per-step effect
"""
import json, math, itertools

H = 8
NPRIME = 2 * H
CEIL = (4 * H) ** (H // 2)              # 32^4 = 1048576 = 2^20
CEIL_ODD = (4 * H - 3) ** (H // 2)      # 29^4, valid only on odd-norm vectors
ROOT = int(math.isqrt(CEIL))            # 1024


def negmul(a, b, h):
    c = [0] * h
    for i in range(h):
        ai = a[i]
        if not ai:
            continue
        for j in range(h):
            bj = b[j]
            if not bj:
                continue
            k = i + j
            if k < h:
                c[k] += ai * bj
            else:
                c[k - h] -= ai * bj
    return c


def tower_norm(w):
    w = list(w)
    h = len(w)
    while h > 1:
        wm = [w[i] if i % 2 == 0 else -w[i] for i in range(h)]
        p = negmul(w, wm, h)
        w = [p[2 * i] for i in range(h // 2)]
        h //= 2
    return w[0]


LIM = ROOT + 1
sieve = bytearray([1]) * (LIM + 1)
sieve[0] = sieve[1] = 0
for i in range(2, int(LIM ** .5) + 1):
    if sieve[i]:
        sieve[i * i::i] = bytearray(len(sieve[i * i::i]))
SMALL = [i for i in range(2, LIM + 1) if sieve[i]]


def factor(n):
    f = {}
    for p in SMALL:
        if p * p > n:
            break
        while n % p == 0:
            f[p] = f.get(p, 0) + 1
            n //= p
    if n > 1:
        f[n] = f.get(n, 0) + 1
    return f


def v2(n):
    k = 0
    while n % 2 == 0:
        n //= 2
        k += 1
    return k


maxnorm = maxnorm_odd = 0
lem1_viol = lem1_odd_viol = 0
norms = set()
for w in itertools.product(range(-2, 3), repeat=H):
    if not any(w):
        continue
    N = tower_norm(w)
    E = sum(x * x for x in w)
    if N <= 0 or N > E ** (H // 2) or N > CEIL:
        lem1_viol += 1
    if sum(w) % 2:
        if N > CEIL_ODD:
            lem1_odd_viol += 1
        maxnorm_odd = max(maxnorm_odd, N)
    maxnorm = max(maxnorm, N)
    norms.add(N)

lem2_viol = 0
badmult = {}
for N in norms:
    f = factor(N)
    if sum(e for p, e in f.items() if p > ROOT) > 1:
        lem2_viol += 1
    for p in f:
        if p > 2:
            badmult[p] = badmult.get(p, 0) + 1

BAD = sorted(badmult)
BAD1 = [p for p in BAD if p % NPRIME == 1]

print("=== calibration + LEM checks (h=%d, N'=%d) ===" % (H, NPRIME))
print("distinct nonzero norms CLASSES :", len(norms), "   (round-25 ground truth: 1450)")
print("MAXNORM (full box)             :", maxnorm, "  CEIL=(4h)^{h/2} =", CEIL,
      " ratio %.4f" % (maxnorm / CEIL))
print("MAXNORM (odd-norm box)         :", maxnorm_odd, "  (4h-3)^{h/2} =", CEIL_ODD,
      " ratio %.4f" % (maxnorm_odd / CEIL_ODD))
print("LEM-1 violations (Norm<=E^{h/2} and <=CEIL) :", lem1_viol)
print("LEM-1odd violations (odd-norm <= (4h-3)^{h/2}) :", lem1_odd_viol)
print("LEM-2 violations (two prime factors > %d)   :" % ROOT, lem2_viol)
print("odd prime divisors             :", len(BAD),
      "  (round-25: 554)   = 1 mod N':", len(BAD1), " (round-25: 536)")
print("max bad prime                  :", max(BAD1), " (round-25: 463249)")

ORB = 2 * H * H
burn = 5 ** H / ORB + 5 ** (H // 2)
print("Burnside orbit bound on CLASSES: 5^h/%d + 5^{h/2} = %.1f  (>= %d ? %s)"
      % (ORB, burn, len(norms), len(norms) <= burn))

LO, HI = 2 ** NPRIME, CEIL
sv = bytearray([1]) * (HI + 1)
sv[0] = sv[1] = 0
for i in range(2, int(HI ** .5) + 1):
    if sv[i]:
        sv[i * i::i] = bytearray(len(sv[i * i::i]))
allp = [p for p in range(LO + 1, HI + 1) if sv[p] and p % NPRIME == 1]
badw = [p for p in BAD1 if LO < p <= HI]
PI, BC = len(allp), len(badw)
print()
print("=== THM-SPARSE at the toy: W_ADM(16) = (2^16, %d] ===" % HI)
print("PI(W) = %d    BADCOUNT(W) = %d    measured BADDENS = %.5f" % (PI, BC, BC / PI))
print("proved bound  bulletproof 5^h/PI      : %.3f  %s"
      % (5 ** H / PI, "VACUOUS" if 5 ** H / PI >= 1 else "ok"))
print("proved bound  Burnside/PI             : %.3f  %s"
      % (burn / PI, "VACUOUS" if burn / PI >= 1 else "ok"))
print("proved bound  exact CLASSES/PI        : %.3f" % (len(norms) / PI))
print("over-prediction (Burnside bound / truth): %.1f x" % (burn / BC))

print()
print("=== v_2-graded (the uniformity clause) — toy VSPARSE ===")
print(" v   PI_v   BAD_v   BADDENS_v    proved(Burnside)/PI_v")
rows = []
for v in range(4, 17):
    pv = [p for p in allp if v2(p - 1) >= v]
    if not pv:
        break
    bv = [p for p in badw if v2(p - 1) >= v]
    rows.append((v, len(pv), len(bv), len(bv) / len(pv), burn / len(pv)))
    print("%2d %6d %7d  %10.5f  %14.3f" % rows[-1])
vs = [r[0] for r in rows if r[4] < 1]
print("VSPARSE(toy, N'=16) =", max(vs) if vs else "none (bound vacuous at every v)")

# ---- F2: Cochran-Armitage
def ca(strata):
    U = V = 0.0
    for st in strata:
        n = sum(a for _, _, a in st)
        b = sum(x for _, x, _ in st)
        if n == 0 or b == 0 or b == n:
            continue
        p = b / n
        vbar = sum(a * v for v, _, a in st) / n
        svv = sum(a * (v - vbar) ** 2 for v, _, a in st)
        U += sum(v * (x - a * p) for v, x, a in st)
        V += p * (1 - p) * svv
    return (U / math.sqrt(V), 2.80 / math.sqrt(V)) if V > 0 else (None, None)


prof_bad, prof_all = {}, {}
for p in BAD1:
    prof_bad[v2(p - 1)] = prof_bad.get(v2(p - 1), 0) + 1
lim2 = max(BAD1)
for p in range(2, lim2 + 1):
    if sv[p] and p % NPRIME == 1:
        prof_all[v2(p - 1)] = prof_all.get(v2(p - 1), 0) + 1
VMAX = 12
pooled = [[(v, prof_bad.get(v, 0), prof_all.get(v, 0)) for v in range(4, VMAX + 1)]]
Z, mde = ca(pooled)
print()
print("=== F2 registered falsifier: trend in BADFRAC8(v) ===")
print("bad v=4..12 :", [prof_bad.get(v, 0) for v in range(4, VMAX + 1)],
      "  (round-25: [274,125,74,38,11,8,4,1,1])")
print("all v=4..12 :", [prof_all.get(v, 0) for v in range(4, VMAX + 1)],
      "  (round-25: [2398,1214,604,294,152,77,38,11,11])")
print("pooled BADFRAC8 = %.4f  (round-25: 0.1115)"
      % (sum(prof_bad.get(v, 0) for v in range(4, VMAX + 1))
         / sum(prof_all.get(v, 0) for v in range(4, VMAX + 1))))
print("pooled     Cochran-Armitage Z = %+.3f  (falsify if |Z|>=1.96)" % Z)
print("           80%%-power min detectable per-v-step factor = %.4f" % math.exp(mde))

# dyadic-stratified
bad_by = {}
for p in BAD1:
    bad_by.setdefault((p.bit_length() - 1, v2(p - 1)), 0)
    bad_by[(p.bit_length() - 1, v2(p - 1))] += 1
all_by = {}
for p in range(2, lim2 + 1):
    if sv[p] and p % NPRIME == 1:
        k = (p.bit_length() - 1, v2(p - 1))
        all_by[k] = all_by.get(k, 0) + 1
strata = []
for j in range(4, 20):
    strata.append([(v, bad_by.get((j, v), 0), all_by.get((j, v), 0))
                   for v in range(4, VMAX + 1)])
Zs, mdes = ca(strata)
print("stratified Cochran-Armitage Z = %+.3f  80%%-power min per-step factor %.4f"
      % (Zs, math.exp(mdes)))

json.dump({"classes": len(norms), "maxnorm": maxnorm, "CEIL": CEIL,
           "maxnorm_odd": maxnorm_odd, "CEIL_ODD": CEIL_ODD,
           "nbad": len(BAD), "nbad_adm": len(BAD1), "PI": PI, "BADCOUNT": BC,
           "burnside": burn, "lem1": lem1_viol, "lem1odd": lem1_odd_viol,
           "lem2": lem2_viol, "Z_pooled": Z, "Z_strat": Zs,
           "mde_pooled": math.exp(mde), "mde_strat": math.exp(mdes),
           "rows_v": rows},
          open("notes/pilots_20260809/b_sparsity_pose/state_d1_toy.json", "w"))
print("\nwrote state_d1_toy.json")
