"""D2 — the LINEAR general-w form of LAW 2.

s is a homomorphism (P1, proved: Norm multiplicative + (1+2ha)(1+2hb) =
1+2h(a+b) mod 4h), and s(w) depends only on w mod 4 = w mod pi^{2h}
(pi = zeta-1, v_pi(2) = h).  The group (R/4)^* = 1 + pi R has the canonical
filtration with quotients (1+pi^k R)/(1+pi^{k+1} R) = R/pi = F_2 generated by
1+pi^k, so every odd-norm w has a UNIQUE expansion

    w = prod_{k=1}^{2h-1} (1+pi^k)^{eps_k}   (mod pi^{2h}),  eps_k in {0,1}

and therefore   s(w) = sum_k eps_k * c_k,   c_k := s(1+pi^k).

This script computes the table c_k and verifies the law on random w by
extracting the digits (all arithmetic in Z/4 on x-coordinates; v_pi read off
the pi-basis, where the valuations i + h*v_2(b_i) are pairwise distinct).
"""
import random

random.seed(20260809)


def negmul(a, b, h, mod=None):
    c = [0] * h
    for i in range(h):
        ai = a[i]
        if not ai:
            continue
        for j in range(h):
            bj = b[j]
            if not bj:
                continue
            k = i + j
            if k < h:
                c[k] += ai * bj
            else:
                c[k - h] -= ai * bj
    if mod:
        c = [v % mod for v in c]
    return c


def tower_norm(w):
    w = list(w)
    h = len(w)
    while h > 1:
        wm = [w[i] if i % 2 == 0 else -w[i] for i in range(h)]
        p = negmul(w, wm, h)
        w = [p[2 * i] for i in range(h // 2)]
        h //= 2
    return w[0]


def s_of(w):
    h = len(w)
    N = tower_norm(w)
    assert N % 2 == 1
    return ((N - 1) // (2 * h)) % 2


def pipow(k, h, mod=None):
    """(x-1)^k in Z[x]/(x^h+1)"""
    r = [0] * h
    r[0] = 1
    base = [0] * h
    base[0] = -1
    if h > 1:
        base[1] = 1
    for _ in range(k):
        r = negmul(r, base, h, mod)
    return r


def to_pi_basis(z, h):
    """b with z = sum b_i (x-1)^i, exact over Z (unitriangular)."""
    z = list(z)
    b = []
    cur = z
    for i in range(h):
        # Taylor expansion at x = 1: b_i = cur(1), then divide by (x-1)
        b.append(sum(cur) if len(cur) else 0)
        # divide (cur - b_i) by (x-1): coefficients of quotient
        rem = cur[:]
        rem[0] -= b[-1]
        q = [0] * max(len(rem) - 1, 0)
        acc = 0
        for j in range(len(rem) - 1, 0, -1):
            acc += rem[j]
            q[j - 1] = acc
        cur = q
    return b


def vpi(z, h, cap):
    b = to_pi_basis(z, h)
    best = cap
    for i, bi in enumerate(b):
        bi %= 4
        if bi == 0:
            continue
        v2 = 0 if bi % 2 else (1 if bi % 4 else 2)
        best = min(best, i + h * v2)
    return best


for h in (4, 8, 16, 32):
    tab = []
    for k in range(1, 2 * h):
        w = pipow(k, h)
        w[0] += 1
        tab.append(s_of(w))
    print("h=%2d  c_k (k=1..%d): %s" % (h, 2 * h - 1, "".join(map(str, tab))))
    print("      support K = %s" % [k + 1 for k, v in enumerate(tab) if v])

    # verify the digit law on random odd-norm w
    bad = n = 0
    while n < 200:
        w = [random.randint(-4, 4) for _ in range(h)]
        if sum(w) % 2 == 0:
            continue
        n += 1
        target = s_of(w)
        t = [v % 4 for v in w]
        acc = 0
        for k in range(1, 2 * h):
            z = t[:]
            z[0] = (z[0] - 1) % 4
            if all(v == 0 for v in z):
                break
            if vpi(z, h, 2 * h) == k:
                acc ^= tab[k - 1]
                # multiply by (1+pi^k)^{-1} = sum_j (-pi^k)^j mod pi^{2h}
                J = -(-2 * h // k)
                inv = [0] * h
                inv[0] = 1
                term = [0] * h
                term[0] = 1
                pk = pipow(k, h, 4)
                for _ in range(1, J + 1):
                    term = negmul(term, pk, h, 4)
                    term = [(-v) % 4 for v in term]
                    inv = [(inv[i] + term[i]) % 4 for i in range(h)]
                t = negmul(t, inv, h, 4)
        if acc != target:
            bad += 1
    print("      digit-law check on %d random w: violations %d" % (n, bad))
