#!/usr/bin/env python3
"""ROOT-INDEPENDENCE and ORBIT STRUCTURE of the folded box witness set.

THEOREM (elementary, stated so the certificate's scope is unambiguous).
In R = Z[x]/(x^h+1) with h = N'/2 a power of two, let tau_s : x -> x^s for
s odd.  For w = sum_j w_j x^j, tau_s(w) = sum_j w_j x^{sj mod 2h}, and
x^m = -x^{m-h} for h <= m < 2h, so tau_s permutes the coefficients up to
sign: it is a SIGNED PERMUTATION of Z^h.  Hence

   ||tau_s(w)||_inf = ||w||_inf   and   ||tau_s(w)||_1 = ||w||_1,

so tau_s maps the folded box {-2..2}^h onto itself, and it maps
Lambda_{p,rho} = {w : w(rho) = 0 mod p} onto Lambda_{p,rho^t} with
t = s^{-1} mod 2h.  Therefore:

   the box-emptiness verdict at (p, rho) is THE SAME for every primitive
   2h-th root rho in F_p.

Consequences used in the report:
 (1) the E1-128 certificate does not depend on which primitive 128th root
     is used -- the pinned rho_128 is used anyway, so the certificate is
     tied to the literal constant, but a replayer using any other
     primitive root gets the same verdict;
 (2) multiplication by x (the negacyclic shift sigma) also preserves
     Lambda_p and the box, so witnesses come in orbits under the group
     generated by sigma and -1, of order dividing 2h.  Observed orbit
     sizes are a structural cross-check on the witness SET.
"""
import os
import sys

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.normpath(os.path.join(HERE, '..', 'ge_floor_falsifier')))
import latlib as LL                                       # noqa: E402


def sigma(w):
    """multiplication by x in Z[x]/(x^h+1)."""
    h = len(w)
    return tuple([-w[h - 1]] + list(w[:h - 1]))


def tau(w, s):
    """x -> x^s, s odd."""
    h = len(w)
    out = [0] * h
    for j, c in enumerate(w):
        m = (s * j) % (2 * h)
        if m < h:
            out[m] += c
        else:
            out[m - h] -= c
    return tuple(out)


def orbits(ws):
    ws = set(ws)
    seen = set()
    out = []
    for w in sorted(ws):
        if w in seen:
            continue
        o = set()
        cur = w
        for _ in range(2 * len(w)):
            o.add(cur)
            o.add(tuple(-t for t in cur))
            cur = sigma(cur)
        o &= ws
        seen |= o
        out.append(sorted(o))
    return out


print("== witness ORBIT structure under <sigma, -1> (order 2h) ==")
for (h, p, L) in [(4, 137, 8), (8, 12289, 16), (8, 463249, 16)]:
    z = LL.zeta_of_order(2 * h, p)
    cvec = [pow(z, j, p) for j in range(h)]
    ws = LL.brute_box(h, p, cvec, L)
    ob = orbits(ws)
    print("   h=%-3d p=%-8d 2l'=%-3d : %d witnesses = %d orbit(s) of size %s "
          "(group order 2h = %d)"
          % (h, p, L, len(ws), len(ob), [len(o) for o in ob], 2 * h))
    ok = all(sigma(w) in set(ws) for w in ws)
    print("        closed under sigma: %s ; closed under negation: %s"
          % (ok, all(tuple(-t for t in w) in set(ws) for w in ws)))

print("\n== root-independence, verified computationally ==")
for (h, p, L) in [(4, 137, 8), (8, 12289, 16), (8, 463249, 16), (8, 463457, 16)]:
    N = 2 * h
    z0 = LL.zeta_of_order(N, p)
    counts = []
    for s in range(1, N, 2):
        zs = pow(z0, s, p)
        if pow(zs, h, p) != p - 1:
            continue
        cv = [pow(zs, j, p) for j in range(h)]
        counts.append(len(LL.brute_box(h, p, cv, L)))
    print("   h=%-3d p=%-8d : witness counts over ALL %d primitive %d-th "
          "roots = %s -> %s"
          % (h, p, len(counts), N, sorted(set(counts)),
             "ROOT-INDEPENDENT" if len(set(counts)) == 1 else "**VARIES**"))

print("\n== tau_s is a signed permutation (checked on random box vectors) ==")
import random
rnd = random.Random(1)
bad = 0
for h in (4, 8, 64):
    for _ in range(200):
        w = tuple(rnd.randint(-2, 2) for _ in range(h))
        for s in (3, 5, 7, 2 * h - 1):
            t = tau(w, s)
            if sorted(abs(a) for a in t) != sorted(abs(a) for a in w):
                bad += 1
print("   violations over 200 random vectors x 4 exponents x h in {4,8,64}: "
      "%d  -> %s" % (bad, "PASS" if bad == 0 else "**FAIL**"))
